// Copyright 2026 PTO-WSP Authors
// SPDX-License-Identifier: MIT

#include "pto/wsp/codegen/pto_runtime_host_build_graph.hpp"

#include <sstream>

namespace pto::wsp::codegen::pto_runtime {

static std::string emit_kernel_config_py(const pto::wsp::ir::Module& module) {
    std::ostringstream out;
    out << "\"\"\"\n"
           "Kernel and orchestration configuration (PTO-WSP generated)\n"
           "\n"
           "This file mirrors pto-runtime's example `kernel_config.py` conventions.\n"
           "\"\"\"\n\n";
    out << "from pathlib import Path\n\n";
    out << "_KERNELS_ROOT = Path(__file__).parent\n\n";
    out << "ORCHESTRATION = {\n";
    out << "    \"source\": str(_KERNELS_ROOT / \"orchestration\" / \"pto_wsp_orch.cpp\"),\n";
    out << "    \"function_name\": \"build_pto_wsp_graph\",\n";
    out << "}\n\n";
    out << "KERNELS = [\n";
    for (size_t i = 0; i < module.kernels.size(); ++i) {
        const auto& k = module.kernels[i];
        out << "    {\"func_id\": " << i << ", \"source\": str(_KERNELS_ROOT / \"aiv\" / \"kernel_" << k.name
            << ".cpp\"), \"core_type\": \"aiv\"},\n";
    }
    out << "]\n";
    return out.str();
}

static std::string emit_orchestration_cpp(const pto::wsp::ir::Module& module) {
    (void)module;
    std::ostringstream out;
    out << "// Generated by PTO-WSP v10 (Phase 1 scaffold)\n";
    out << "// Target: pto-runtime host_build_graph\n";
    out << "//\n";
    out << "// This file is a scaffold: it establishes the integration shape (orchestration .so)\n";
    out << "// but does not yet lower full PTO-WSP schedule/CSP semantics into pto-runtime.\n";
    out << "\n";
    out << "#include \"runtime.h\"\n";
    out << "#include <cstdint>\n";
    out << "\n";
    out << "namespace {\n";
    out << "static int pto_wsp_select_aicpu_scheduler_id(uint64_t task_id) {\n";
    out << "  (void)task_id;\n";
    out << "  // TODO_PTO_RUNTIME_MULTI_AICPU_DISPATCH: map PTO-WSP dispatch(policy) to AICPU scheduler assignment.\n";
    out << "  // pto-runtime host_build_graph does not yet expose a stable API for task→AICPU-shard selection.\n";
    out << "  return 0;\n";
    out << "}\n";
    out << "}  // namespace\n\n";
    out << "extern \"C\" {\n\n";
    out << "int build_pto_wsp_graph(Runtime* runtime, uint64_t* args, int arg_count) {\n";
    out << "  (void)runtime;\n";
    out << "  (void)args;\n";
    out << "  (void)arg_count;\n";
    out << "\n";
    out << "  // Phase 1 scaffold: host builds a static task graph.\n";
    out << "  // Future work will:\n";
    out << "  // - allocate tensors via runtime->host_api\n";
    out << "  // - add tasks (runtime->add_task) and deps (runtime->add_successor)\n";
    out << "  // - record output tensors for copy-back\n";
    out << "  // - plumb schedule metadata and CSP edges into runtime semantics\n";
    out << "\n";
    out << "  // Silence unused placeholder hook.\n";
    out << "  (void)pto_wsp_select_aicpu_scheduler_id(0);\n";
    out << "  return 0;\n";
    out << "}\n\n";
    out << "}  // extern \"C\"\n";
    return out.str();
}

static std::string emit_stub_aiv_kernel_cpp(const std::string& name) {
    std::ostringstream out;
    out << "// Generated by PTO-WSP v10 (Phase 1 scaffold)\n";
    out << "// Target: pto-runtime AIV kernel\n\n";
    out << "#include <cstdint>\n";
    out << "#include <pto/pto-inst.hpp>\n";
    out << "#include <pto/common/constants.hpp>\n\n";
    out << "using namespace pto;\n\n";
    out << "#ifndef __gm__\n";
    out << "#define __gm__\n";
    out << "#endif\n\n";
    out << "#ifndef __aicore__\n";
    out << "#define __aicore__\n";
    out << "#endif\n\n";
    out << "extern \"C\" __aicore__ __attribute__((always_inline)) void " << name << "(__gm__ int64_t* args) {\n";
    out << "  (void)args;\n";
    out << "  // TODO: lower PTO-WSP kernel semantics to pto-runtime kernel ABI.\n";
    out << "}\n";
    return out.str();
}

std::map<std::string, std::string> emit_host_build_graph_sources(
    const ir::Module& module,
    const backend::CompileOptions& /*options*/) {
    std::map<std::string, std::string> sources;
    sources.emplace("kernels/kernel_config.py", emit_kernel_config_py(module));
    sources.emplace("kernels/orchestration/pto_wsp_orch.cpp", emit_orchestration_cpp(module));
    for (const auto& k : module.kernels) {
        sources.emplace("kernels/aiv/kernel_" + k.name + ".cpp", emit_stub_aiv_kernel_cpp("kernel_" + k.name));
    }
    return sources;
}

}  // namespace pto::wsp::codegen::pto_runtime

